name: E2E

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build etcdadm
      run: make container-build
    - uses: actions/cache@v2
      with:
        path: ./etcdadm
        key: ${{ runner.os }}-etcdadm-bin-${{ github.sha }}

  cluster-create-phases-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v2
      with:
        path: ./etcdadm
        key: ${{ runner.os }}-etcdadm-bin-${{ github.sha }}
    - name: Run create cluster with etcdadm phases e2e test
      run: ./test/e2e/cluster_phases.sh
