name: E2E

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16' # The Go version to download (if necessary) and use.
    - name: Build etcdadm
      run: make etcdadm
    - uses: actions/cache@v2
      with:
        path: ./etcdadm
        key: ${{ runner.os }}-etcdadm-bin-${{ github.sha }}

  phases-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v2
      with:
        path: ./etcdadm
        key: ${{ runner.os }}-etcdadm-bin-${{ github.sha }}
    - name: Run etcdadm phases e2e test
      run: ./test/e2e/cluster_phases.sh


    
